yassineBundle\Entity\contact:
     type: entity
       table: login
       id:
           id:
               type: integer
               generator: { strategy: AUTO }
       fields:
           username:
               type: string
               length: 100
           password:
               type: string
               lenght: 100